import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ExportMetadata {
  reportName: string;
  generatedDate: string;
  generatedBy: string;
  filtersApplied: Record<string, string>;
  summaryKpis?: Record<string, string | number>;
}

export function exportToExcel(
  metadata: ExportMetadata,
  data: Record<string, any>[],
  fileName?: string
) {
  const wb = XLSX.utils.book_new();

  // Create a clean summary sheet
  const summaryRows: (string | number)[][] = [
    ['REPORT NAME', metadata.reportName],
    ['GENERATED DATE', metadata.generatedDate],
    ['GENERATED BY', metadata.generatedBy],
    [],
    ['APPLIED FILTERS:'],
  ];

  Object.entries(metadata.filtersApplied).forEach(([k, v]) => {
    summaryRows.push([k, v || 'All']);
  });

  if (metadata.summaryKpis && Object.keys(metadata.summaryKpis).length > 0) {
    summaryRows.push([]);
    summaryRows.push(['SUMMARY KEY METRICS:']);
    Object.entries(metadata.summaryKpis).forEach(([k, v]) => {
      summaryRows.push([k, v]);
    });
  }

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // Create the main data sheet
  if (data.length > 0) {
    const wsData = XLSX.utils.json_to_sheet(data);
    XLSX.utils.book_append_sheet(wb, wsData, 'Report Data');
  }

  const safeFileName = (fileName || metadata.reportName).replace(/[^a-zA-Z0-9_-]/g, '_');
  XLSX.writeFile(wb, `${safeFileName}_${new Date().toISOString().split('T')[0]}.xlsx`);
}

export function exportToPDF(
  metadata: ExportMetadata,
  columns: { header: string; dataKey: string }[],
  data: Record<string, any>[],
  fileName?: string
) {
  const doc = new jsPDF({
    orientation: columns.length > 6 ? 'landscape' : 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Header Banner
  doc.setFillColor(30, 41, 59); // Slate-800
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 22, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('FTE TASK, TIME TRACKING & MANAGEMENT REPORTING SYSTEM', 14, 11);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(metadata.reportName.toUpperCase(), 14, 17);

  // Metadata block
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(8);
  doc.text(`Generated: ${metadata.generatedDate} | By: ${metadata.generatedBy}`, 14, 28);

  // Filters String
  const filterList = Object.entries(metadata.filtersApplied)
    .filter(([_, v]) => Boolean(v) && v !== 'All')
    .map(([k, v]) => `${k}: ${v}`)
    .join(' | ');

  doc.text(`Filters: ${filterList || 'None (Showing All Records)'}`, 14, 33);

  let currentY = 38;

  // Summary KPIs banner if provided
  if (metadata.summaryKpis && Object.keys(metadata.summaryKpis).length > 0) {
    const kpiEntries = Object.entries(metadata.summaryKpis);
    const kpiText = kpiEntries.map(([k, v]) => `${k}: ${v}`).join('    •    ');
    
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(14, currentY, doc.internal.pageSize.getWidth() - 28, 9, 1.5, 1.5, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(8);
    doc.text(`Summary: ${kpiText}`, 18, currentY + 6);
    currentY += 14;
  }

  // Generate Table
  const tableRows = data.map(item => {
    return columns.map(col => {
      const val = item[col.dataKey];
      return val !== undefined && val !== null ? String(val) : '-';
    });
  });

  autoTable(doc, {
    startY: currentY,
    head: [columns.map(c => c.header)],
    body: tableRows,
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 7.5,
      cellPadding: 2,
      textColor: [30, 41, 59],
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: [79, 70, 229], // Indigo 600
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (dataInfo) => {
      // Footer page numbers
      const str = `Page ${doc.getNumberOfPages()}`;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        str,
        doc.internal.pageSize.getWidth() - 25,
        doc.internal.pageSize.getHeight() - 8
      );
    },
  });

  const safeFileName = (fileName || metadata.reportName).replace(/[^a-zA-Z0-9_-]/g, '_');
  doc.save(`${safeFileName}_${new Date().toISOString().split('T')[0]}.pdf`);
}
